#define QUITSUR	"Biztos vagy benne,hogy\n"\
		"ki szeretnel lepni ebbol a jatekbol?"

#define CURGAME	"Te vagy jelenleg\n"\
		"egy jatekban. Folytatas ki fogja\n"\
		"torolni a regi jatekot. Rendben?"

#define GAMESVD	"Van mar egy jatek\n"\
		"ebben a mentett pozicioban.\n"\
		"      Felulirod?"

#define ENDGAMESTR	"Biztos vagy benne,hogy\n"\
					"be akarod fejezni a jatekot\n"\
					"amivel jatszol? (Y or N):"

#define STR_NG	"Uj jatek"
#define	STR_SD	"Hang"
#define	STR_CL	"Iranyitas"
#define	STR_LG	"Jatek betoltese"
#define	STR_SG	"Jatek mentese"
#define	STR_CV	"Nezet valtasa"
#define	STR_VS	"Pontszamok"
#define STR_EG	"Jatek vege"
#define	STR_BD	"Vissza a bemutato"
#define STR_QT	"Kilepes"

#define STR_LOADING	"Betoltes"
#define STR_SAVING	"Mentes"

#define STR_GAME	" jatekba"
#define STR_DEMO	" bemutatoba"
#define STR_LGC		"Toltse be a jatekot\n\""
#define STR_EMPTY	"Ures"
#define STR_CALIB	"Kalibralas"
#define STR_JOYST	"Botkormany"
#define STR_MOVEJOY	"Mozgasd a botkormanyt\nbal felsobe es\nnyomd a 0-as gombot\n"
#define STR_MOVEJOY2 "Mozgasd a botkormanyt\njobb alsoba es\nnyomd az 1-es gombot\n"
#define STR_ESCEXIT	"ESC kilepeshez"

#define STR_NONE	"Semmi"
#define	STR_PC		"Gepi hangszoro"
#define	STR_ALSB	"Rogton./hang sugarveto"
#define	STR_DISNEY	"Disney hangforras"
#define	STR_SB		"Hang sugarveto"

#define	STR_MOUSEEN	"Eger engedelyezve"
#define	STR_JOYEN	"Botkormany engedelyezve"
#define	STR_PORT2	"Hasznald botk. 2.portjat"
#define	STR_GAMEPAD	"Sulyos jatekkormany eng."
#define	STR_SENS	"Eger erzekenysege"
#define	STR_CUSTOM	"Iranyitasok testreszabasa"

#define	STR_DADDY	"Kerlek ne bantsatok!"
#define	STR_HURTME	"Kerek egy kis sort."
#define	STR_BRINGEM	"Szembe nezek a dolgokkal."
#define	STR_DEATH	"Ugy is en vagyok a kiraly!"

#define	STR_MOUSEADJ	"Allitsd be az eger erzekenyseget"
#define STR_SLOW	"Lassu"
#define STR_FAST	"Gyors"

#define	STR_CRUN	"Futas"
#define STR_COPEN	"Nyitas"
#define STR_CFIRE	"Loves"
#define STR_CSTRAFE	"Oldalazas"

#define	STR_LEFT	"Bal"
#define	STR_RIGHT	"Jobb"
#define	STR_FRWD	"Elore"
#define	STR_BKWD	"Hatra"
#define	STR_THINK	"Gondolkodas"

#define STR_SIZE1	"Hasznald a nyilakat a meretezeshez"
#define STR_SIZE2	"ENTER elfogadashoz"
#define STR_SIZE3	"ESC visszavonashoz"

#define STR_YOUWIN	"nyertel!"

#define STR_TOTALTIME	"teljes ido"

#define STR_RATKILL	 	    "oles    %"
#define STR_RATSECRET  	  "titkos    %"
#define STR_RATTREASURE	"kincs       %"

#define STR_BONUS	"plusz"
#define STR_TIME	"ido"
#define STR_PAR		" atlag"

#define STR_RAT2KILL            "olesi ararny      %"
#define STR_RAT2SECRET  	  "titkos arany      %"
#define STR_RAT2TREASURE	"kincs arany       %"

#define STR_DEFEATED	"legyozve!"

#define STR_CHEATER1	"Most van 100% eleterod,"
#define STR_CHEATER2    "300 tolteny es minden kulcs!"
#define STR_CHEATER3	"Ne feledd,hogy alapvetoen"
#define STR_CHEATER4	"megszuntetted az eselyt,"
#define STR_CHEATER5	"hogy magas pontszamot kapj!"

#define STR_NOSPACE1	"Nincs eleg hely"
#define STR_NOSPACE2	"a lemezeden menteni a jatekot!"

#define STR_SAVECHT1	"A mentett jatek fajlod"
#define STR_SAVECHT2	"mondhatni,hogy \"megserult\"."
#define STR_SAVECHT3	"De hagyom,hogy folytasd es"
#define STR_SAVECHT4	"jatszatni egyebkent...."

#define	STR_SEEAGAIN	"Lassuk meg egyszer!"

